version: '3'

services:
  glances:
    image: docker.io/nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host
    ports:
      - "61208:61208"
    entrypoint: ["glances", "-w"]
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
